### ISSUE TITLE
Minor error in example

### ISSUE THREAD

**Issue by krFritsch** [ncgeib/pypret#1]
_Very minor Issue, quickly fixable._

**docs/getting_started.rst** in line 66:
`ret = pypret.Retriever(pnps, "copra", verbose=True, max_iterations=300)`

The argument max_iterations has no effect. 

According to the documentation in **pypret/retrieval/retriever.py** in line 291 it should be maxiter instead.

**Comment by ncgeib** [comment]
Thanks! Fixed in https://github.com/ncgeib/pypret/commit/cf4068ed8bcc2bc7e35e17db9ea6da0c9c99538b
